### ISSUE TITLE
As a user I would like to be able to filter lessons by tags

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#62]
This is an epic issue. List of individual issues needed to achieve this epic are below:

- [x] Add lesson tags logic #59 
- [ ] Modify UI allowing user to add lesson tags (#60)
- [ ] Implement lesson tag filtering #61

**Comment by 1219aks** [comment]
Hi, can you assign me this task please.
